package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, 29 April, 2026 11:29:25 AM IST
*/

public interface CalcOperations 
{
  float sum (float a, float b);
  float sub (float a, float b);
  float mul (float a, float b);
  float div (float a, float b) throws CalcApp.CalcPackage.DivisionByZero;
} // interface CalcOperations
